
import java.awt.Color;
import java.awt.Image;
import java.sql.Statement;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Admin
 */
public class setupdata extends javax.swing.JFrame {
java.sql.Connection conn = null;
ResultSet rs = null;
Statement st;

    /**
     * Creates new form setupdata
     */
    public setupdata() {
        initComponents();
        scaleImage();
        scaleImage1();
    }
        public setupdata(String para){
        initComponents();
        scaleImage();
        scaleImage1();
        jPanel2.setBackground(new Color(0,0,0,150));
        account.setText(para);
        String user = account.getText();
        int elec1 = 0,inte1 = 0,busi1 = 0,staf1 = 0,room1 = 0;
        try{
            conn = DriverManager.getConnection("jdbc:derby://localhost:1527/bactong","bactong","bactong");
            st = conn.createStatement();
            rs = st.executeQuery("SELECT * FROM BACTONG.EXP WHERE USERNAME = '"+user+"'");
            while(rs.next()){
                elec1 = rs.getInt(2);
                elec.setText(""+elec1);
                inte1 = rs.getInt(3);
                inte.setText(""+inte1);
                busi1 = rs.getInt(4);
                busi.setText(""+busi1);
                staf1 = rs.getInt(5);
                staf.setText(""+staf1);
                room1 = rs.getInt(6);
                room.setText(""+room1);
                    break;
                }
        }
            catch (Exception ex){
                    Logger.getLogger(login.class.getName()).log(Level.SEVERE,null,ex);
                    final JPanel panel = new JPanel();
                    JOptionPane.showMessageDialog(panel,"No Data to be Computed!!","Database Notice", JOptionPane.ERROR_MESSAGE);
                    }
    }
public void scaleImage(){
        ImageIcon icon = (ImageIcon) jLabel1.getIcon();
        Image img = icon.getImage();
        Image imgScale = img.getScaledInstance(jLabel1.getWidth(),jLabel1.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaledIcon = new ImageIcon(imgScale);
        jLabel1.setIcon(scaledIcon);
   
    }
public void scaleImage1(){
        ImageIcon icon = (ImageIcon) apply.getIcon();
        Image img = icon.getImage();
        Image imgScale = img.getScaledInstance(apply.getWidth(),apply.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaledIcon = new ImageIcon(imgScale);
        apply.setIcon(scaledIcon);
        cancel.setIcon(scaledIcon);
        reset.setIcon(scaledIcon);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        reset = new javax.swing.JButton();
        apply = new javax.swing.JButton();
        elec = new javax.swing.JTextField();
        inte = new javax.swing.JTextField();
        busi = new javax.swing.JTextField();
        staf = new javax.swing.JTextField();
        room = new javax.swing.JTextField();
        cancel = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        account = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setLayout(null);

        reset.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        reset.setText("Reset");
        reset.setContentAreaFilled(false);
        reset.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });
        jPanel2.add(reset);
        reset.setBounds(80, 220, 80, 30);

        apply.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        apply.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BACTONG COMP SHOP/BACTONG COMP SHOP/222026_preview.png"))); // NOI18N
        apply.setText("Apply");
        apply.setContentAreaFilled(false);
        apply.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        apply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                applyActionPerformed(evt);
            }
        });
        jPanel2.add(apply);
        apply.setBounds(260, 220, 80, 30);

        elec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                elecActionPerformed(evt);
            }
        });
        jPanel2.add(elec);
        elec.setBounds(220, 60, 90, 25);
        jPanel2.add(inte);
        inte.setBounds(220, 90, 90, 25);
        jPanel2.add(busi);
        busi.setBounds(220, 120, 90, 25);
        jPanel2.add(staf);
        staf.setBounds(220, 150, 90, 25);
        jPanel2.add(room);
        room.setBounds(220, 180, 90, 25);

        cancel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cancel.setText("Cancel");
        cancel.setContentAreaFilled(false);
        cancel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });
        jPanel2.add(cancel);
        cancel.setBounds(170, 220, 80, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 255, 255));
        jLabel3.setText("Internet:");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(130, 90, 70, 17);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 255, 255));
        jLabel8.setText("Electricity:");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(125, 60, 80, 20);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 255, 255));
        jLabel4.setText("Business Tax:");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(100, 120, 101, 17);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 255, 255));
        jLabel5.setText("Staff Payment:");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(90, 150, 103, 17);

        jLabel6.setFont(new java.awt.Font("Calisto MT", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 255, 255));
        jLabel6.setText("Setup Expenses");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(90, 20, 200, 29);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 255, 255));
        jLabel7.setText("Room Rent Payment:");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(45, 180, 150, 17);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 255, 255));
        jLabel9.setText("per Year");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(320, 120, 80, 20);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 255, 255));
        jLabel10.setText("per Day");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(320, 150, 80, 20);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(204, 255, 255));
        jLabel11.setText("per Month");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(320, 180, 80, 20);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 255, 255));
        jLabel2.setText("per Month");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(320, 90, 80, 20);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(204, 255, 255));
        jLabel12.setText("per kWh");
        jPanel2.add(jLabel12);
        jLabel12.setBounds(320, 60, 80, 20);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(20, 20, 440, 270);

        jLabel13.setFont(new java.awt.Font("Times New Roman", 2, 11)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(204, 255, 255));
        jLabel13.setText("Username:");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(10, 290, 60, 20);

        account.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        account.setForeground(new java.awt.Color(204, 255, 255));
        jPanel1.add(account);
        account.setBounds(60, 290, 210, 20);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BACTONG COMP SHOP/BACTONG COMP SHOP/istockphoto-1166329039-170667a.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 480, 320);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 483, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void elecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_elecActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_elecActionPerformed

    private void applyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_applyActionPerformed
        // TODO add your handling code here:
        String electricity = elec.getText();
        String internet = inte.getText();
        String business = busi.getText();
        String staff = staf.getText();
        String rent = room.getText();
        String user = account.getText();
        if (electricity != null && internet != null && business != null && staff != null && rent != null){
            try{
                conn = DriverManager.getConnection("jdbc:derby://localhost:1527/bactong","bactong","bactong");
                st = conn.createStatement();
                st.executeUpdate("UPDATE BACTONG.EXP SET ELECTRICITY = "+electricity+", INTERNET = "+internet+", BUSINESSTAX = "+business+", STAFFPAYMENT = "+staff+", ROOMRENTPAYMENT = "+rent+" WHERE USERNAME = '"+user+"'");
                final JPanel panel = new JPanel();
                JOptionPane.showMessageDialog(panel,"Shop Expenses Registered","Shop Expenses Notice", JOptionPane.INFORMATION_MESSAGE);
                String msg = account.getText();
                dispose();
                home info = new home(msg);
                info.setVisible(true);
            }
            catch (Exception ex){
                Logger.getLogger(login.class.getName()).log(Level.SEVERE,null,ex);
                final JPanel panel = new JPanel();
                JOptionPane.showMessageDialog(panel,"Please fill out all the box with numbers,\nInput 0 if none","Shop Expenses Notice", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_applyActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        // TODO add your handling code here:
        elec.setText("");
        inte.setText("");
        busi.setText("");
        staf.setText("");
        room.setText("");
    }//GEN-LAST:event_resetActionPerformed

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        // TODO add your handling code here:
        String msg = account.getText();
                dispose();
                home info = new home(msg);
                info.setVisible(true);
    }//GEN-LAST:event_cancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(setupdata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(setupdata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(setupdata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(setupdata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new setupdata().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel account;
    private javax.swing.JButton apply;
    private javax.swing.JTextField busi;
    private javax.swing.JButton cancel;
    private javax.swing.JTextField elec;
    private javax.swing.JTextField inte;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton reset;
    private javax.swing.JTextField room;
    private javax.swing.JTextField staf;
    // End of variables declaration//GEN-END:variables
}
