
import java.awt.Color;
import java.awt.Image;
import java.sql.Statement;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Admin
 */
public class setupdata2 extends javax.swing.JFrame {
java.sql.Connection conn = null;
ResultSet rs = null;
Statement st;
    /**
     * Creates new form setupdata2
     */
    public setupdata2() {
        initComponents();
        scaleImage();
        scaleImage1();
    }
        public setupdata2(String para){
        initComponents();
        scaleImage();
        scaleImage1();
        account.setText(para);
        jPanel2.setBackground(new Color(0,0,0,150));
        String user = account.getText();
        String comp1, pric1, serv1, watt1, swatt1;
        try{
            conn = DriverManager.getConnection("jdbc:derby://localhost:1527/bactong","bactong","bactong");
            st = (Statement)conn.createStatement();
            rs = st.executeQuery("SELECT * FROM BACTONG.SETUP WHERE USERNAME = '"+user+"'");
            while(rs.next()){
                comp1 = rs.getString(2);
                comp.setText(comp1);
                pric1 = rs.getString(3);
                pric.setText(pric1);
                serv1 = rs.getString(4);
                serv.setText(serv1);
                watt1 = rs.getString(5);
                watt.setText(watt1);
                swatt1 = rs.getString(6);
                swatt.setText(swatt1);
                    break;
                }
        }
            catch (Exception ex){
                    Logger.getLogger(login.class.getName()).log(Level.SEVERE,null,ex);
                    final JPanel panel = new JPanel();
                    JOptionPane.showMessageDialog(panel,"No Data to be Computed!!","Database Notice", JOptionPane.ERROR_MESSAGE);
                    }
    }
public void scaleImage(){
        ImageIcon icon = new ImageIcon("C:\\Users\\lenov_000\\Desktop\\Project Management 5th year Final\\BACTONG COMP SHOP\\BACTONG COMP SHOP\\1.jpg");
        Image img = icon.getImage();
        Image imgScale = img.getScaledInstance(jLabel1.getWidth(),jLabel1.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaledIcon = new ImageIcon(imgScale);
        jLabel1.setIcon(scaledIcon);
   
    }
public void scaleImage1(){
        ImageIcon icon = new ImageIcon("C:\\Users\\lenov_000\\Desktop\\Project Management 5th year Final\\BACTONG COMP SHOP\\BACTONG COMP SHOP\\222026_preview.png");
        Image img = icon.getImage();
        Image imgScale = img.getScaledInstance(reset.getWidth(),reset.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaledIcon = new ImageIcon(imgScale);
        apply.setIcon(scaledIcon);
        cancel.setIcon(scaledIcon);
        reset.setIcon(scaledIcon);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        account = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        apply = new javax.swing.JButton();
        cancel = new javax.swing.JButton();
        reset = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        swatt = new javax.swing.JTextField();
        watt = new javax.swing.JTextField();
        serv = new javax.swing.JTextField();
        pric = new javax.swing.JTextField();
        comp = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 2, 11)); // NOI18N
        jLabel7.setText("Username:");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(10, 320, 60, 20);

        account.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jPanel1.add(account);
        account.setBounds(60, 320, 210, 20);

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setLayout(null);

        apply.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        apply.setForeground(new java.awt.Color(204, 255, 255));
        apply.setText("Apply");
        apply.setContentAreaFilled(false);
        apply.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        apply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                applyActionPerformed(evt);
            }
        });
        jPanel2.add(apply);
        apply.setBounds(280, 250, 80, 30);

        cancel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cancel.setForeground(new java.awt.Color(204, 255, 255));
        cancel.setText("Cancel");
        cancel.setContentAreaFilled(false);
        cancel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });
        jPanel2.add(cancel);
        cancel.setBounds(190, 250, 80, 30);

        reset.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        reset.setForeground(new java.awt.Color(204, 255, 255));
        reset.setText("Reset");
        reset.setContentAreaFilled(false);
        reset.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });
        jPanel2.add(reset);
        reset.setBounds(100, 250, 80, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 255, 255));
        jLabel8.setText("Average Sleep Watts per Unit:");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(50, 190, 210, 25);
        jPanel2.add(swatt);
        swatt.setBounds(280, 190, 90, 25);
        jPanel2.add(watt);
        watt.setBounds(280, 160, 90, 25);
        jPanel2.add(serv);
        serv.setBounds(280, 130, 90, 25);
        jPanel2.add(pric);
        pric.setBounds(280, 100, 90, 25);

        comp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                compActionPerformed(evt);
            }
        });
        jPanel2.add(comp);
        comp.setBounds(280, 70, 90, 25);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 255, 255));
        jLabel2.setText("Total Computer Units:");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(100, 70, 153, 20);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 255, 255));
        jLabel3.setText("Price Per Hour:");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(150, 103, 110, 17);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 255, 255));
        jLabel4.setText("Total Server Units:");
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel2.add(jLabel4);
        jLabel4.setBounds(127, 133, 130, 17);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 255, 255));
        jLabel5.setText("Average Watts per Unit:");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(90, 160, 170, 25);

        jLabel6.setFont(new java.awt.Font("Calisto MT", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 255, 255));
        jLabel6.setText("Setup Shop Info");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(90, 20, 280, 29);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(30, 20, 450, 300);
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 510, 360);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 510, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 355, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void compActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_compActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_compActionPerformed

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        // TODO add your handling code here:
        String msg = account.getText();
                dispose();
                home info = new home(msg);
                info.setVisible(true);
    }//GEN-LAST:event_cancelActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        // TODO add your handling code here:
        comp.setText("");
        pric.setText("");
        serv.setText("");
        watt.setText("");
    }//GEN-LAST:event_resetActionPerformed

    private void applyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_applyActionPerformed
        // TODO add your handling code here:
        String computer = comp.getText();
        String price = pric.getText();
        String server = serv.getText();
        String watts = watt.getText();
        String user = account.getText();
        String sleep = swatt.getText();
        if (computer != null && price != null && server != null && watts != null){
            try{
                conn = DriverManager.getConnection("jdbc:derby://localhost:1527/bactong","bactong","bactong");
                st = (Statement)conn.createStatement();
                st.executeUpdate("UPDATE BACTONG.SETUP SET COMPUNITS = "+computer+", PRICEPERHOUR = "+price+", TOTALSERVERUNITS = "+server+", AVERAGEWATT = "+watts+", SLEEPWATT = "+sleep+" WHERE USERNAME = '"+user+"'");
                final JPanel panel = new JPanel();
                JOptionPane.showMessageDialog(panel,"Shop Info Registered","Shop Info Notice", JOptionPane.INFORMATION_MESSAGE);
                String msg = account.getText();
                dispose();
                home info = new home(msg);
                info.setVisible(true);
            }
            catch (Exception ex){
                Logger.getLogger(login.class.getName()).log(Level.SEVERE,null,ex);
                final JPanel panel = new JPanel();
                JOptionPane.showMessageDialog(panel,"Please fill out all the box with numbers,\nInput 0 if none","Shop Info Notice", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_applyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(setupdata2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(setupdata2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(setupdata2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(setupdata2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new setupdata2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel account;
    private javax.swing.JButton apply;
    private javax.swing.JButton cancel;
    private javax.swing.JTextField comp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField pric;
    private javax.swing.JButton reset;
    private javax.swing.JTextField serv;
    private javax.swing.JTextField swatt;
    private javax.swing.JTextField watt;
    // End of variables declaration//GEN-END:variables
}
